### ISSUE TITLE
Edit Post Issue

### ISSUE THREAD

**Issue by alokverma18** [alokverma18/blog#1]
File Preview after uploading a new image while editing the post shows the old image.

**Comment by programmer-rahul** [comment]
Hi, Can you explain this issue so i can start fixing this if you want?

**Comment by alokverma18** [comment]
Hello @programmer-rahul, when we edit the post and change the image, it should change the preview immediately.

**Comment by programmer-rahul** [comment]
Can you attack a screenshot of any other thing .

**Comment by alokverma18** [comment]
You can create an account, then a post and when you edit the post, you'll understand the issue. 
![image](https://github.com/user-attachments/assets/f2d4aa09-6d3b-42e4-8a43-a74073e1147b)
Here, I added a new image, but in preview it still shows the old one because it's coded like that.

**Comment by programmer-rahul** [comment]
@alokverma18 Ok I will try to solve this as soon possible. Assign me
